---
version: '3'
services:
 mysql:
   image: mysql:v2
   restart: always
   container_name: mysql
   volumes:
     - mydb_data:/var/lib/mysql
   environment:
     MYSQL_ROOT_PASSWORD: amit123
     MYSQL_DATABASE: wordpress
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress

 wordpress:
   depends_on:
     - mysql

   container_name: wordpress

   image: wordpress:v2
   ports:
     - "8093:80"
   restart: always
   environment:
     WORDPRESS_DB_HOST: mysql
     WORDPRESS_DB_USER: wordpress
     WORDPRESS_DB_PASSWORD: wordpress
     WORDPRESS_DB_NAME: wordpress

volumes:
 mydb_data: {}